/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClientStatus} from './ClientStatus';
import {DocumentVersion} from './DocumentVersion';

/**
 * The Client model module.
 * @module model/Client
 * @version v1
 */
export class Client {
  /**
   * Constructs a new <code>Client</code>.
   * @alias module:model/Client
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Client</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Client} obj Optional instance to populate.
   * @return {module:model/Client} The populated <code>Client</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Client();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = DocumentVersion.constructFromObject(data['version']);
      if (data.hasOwnProperty('companyId'))
        obj.companyId = ApiClient.convertToType(data['companyId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = ApiClient.convertToType(data['document'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('ie'))
        obj.ie = ApiClient.convertToType(data['ie'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ClientStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('userSellerId'))
        obj.userSellerId = ApiClient.convertToType(data['userSellerId'], 'String');
      if (data.hasOwnProperty('paymentConditionId'))
        obj.paymentConditionId = ApiClient.convertToType(data['paymentConditionId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Client.prototype.id = undefined;

/**
 * @member {Date} createdAt
 */
Client.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
Client.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
Client.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
Client.prototype.userUpdated = undefined;

/**
 * @member {module:model/DocumentVersion} version
 */
Client.prototype.version = undefined;

/**
 * @member {String} companyId
 */
Client.prototype.companyId = undefined;

/**
 * @member {String} name
 */
Client.prototype.name = undefined;

/**
 * @member {String} document
 */
Client.prototype.document = undefined;

/**
 * @member {String} phone
 */
Client.prototype.phone = undefined;

/**
 * @member {String} email
 */
Client.prototype.email = undefined;

/**
 * @member {String} ie
 */
Client.prototype.ie = undefined;

/**
 * @member {String} externalCode
 */
Client.prototype.externalCode = undefined;

/**
 * @member {module:model/ClientStatus} status
 */
Client.prototype.status = undefined;

/**
 * @member {String} userSellerId
 */
Client.prototype.userSellerId = undefined;

/**
 * @member {String} paymentConditionId
 */
Client.prototype.paymentConditionId = undefined;

