/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductGroupStatus} from './ProductGroupStatus';

/**
 * The GetAllProductGroupResponse model module.
 * @module model/GetAllProductGroupResponse
 * @version v1
 */
export class GetAllProductGroupResponse {
  /**
   * Constructs a new <code>GetAllProductGroupResponse</code>.
   * @alias module:model/GetAllProductGroupResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAllProductGroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllProductGroupResponse} obj Optional instance to populate.
   * @return {module:model/GetAllProductGroupResponse} The populated <code>GetAllProductGroupResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAllProductGroupResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ProductGroupStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
GetAllProductGroupResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
GetAllProductGroupResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
GetAllProductGroupResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
GetAllProductGroupResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
GetAllProductGroupResponse.prototype.id = undefined;

/**
 * @member {String} name
 */
GetAllProductGroupResponse.prototype.name = undefined;

/**
 * @member {String} description
 */
GetAllProductGroupResponse.prototype.description = undefined;

/**
 * @member {String} externalCode
 */
GetAllProductGroupResponse.prototype.externalCode = undefined;

/**
 * @member {module:model/ProductGroupStatus} status
 */
GetAllProductGroupResponse.prototype.status = undefined;

