/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PaymentConditionStatus} from './PaymentConditionStatus';

/**
 * The GetAllPaymentConditionResponse model module.
 * @module model/GetAllPaymentConditionResponse
 * @version v1
 */
export class GetAllPaymentConditionResponse {
  /**
   * Constructs a new <code>GetAllPaymentConditionResponse</code>.
   * @alias module:model/GetAllPaymentConditionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAllPaymentConditionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllPaymentConditionResponse} obj Optional instance to populate.
   * @return {module:model/GetAllPaymentConditionResponse} The populated <code>GetAllPaymentConditionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAllPaymentConditionResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('sequence'))
        obj.sequence = ApiClient.convertToType(data['sequence'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = PaymentConditionStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
GetAllPaymentConditionResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
GetAllPaymentConditionResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
GetAllPaymentConditionResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
GetAllPaymentConditionResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
GetAllPaymentConditionResponse.prototype.id = undefined;

/**
 * @member {String} name
 */
GetAllPaymentConditionResponse.prototype.name = undefined;

/**
 * @member {String} externalCode
 */
GetAllPaymentConditionResponse.prototype.externalCode = undefined;

/**
 * @member {Number} sequence
 */
GetAllPaymentConditionResponse.prototype.sequence = undefined;

/**
 * @member {module:model/PaymentConditionStatus} status
 */
GetAllPaymentConditionResponse.prototype.status = undefined;

