/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UserStatus} from './UserStatus';

/**
 * The GetAllUserResponse model module.
 * @module model/GetAllUserResponse
 * @version v1
 */
export class GetAllUserResponse {
  /**
   * Constructs a new <code>GetAllUserResponse</code>.
   * @alias module:model/GetAllUserResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAllUserResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllUserResponse} obj Optional instance to populate.
   * @return {module:model/GetAllUserResponse} The populated <code>GetAllUserResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAllUserResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('documentId'))
        obj.documentId = ApiClient.convertToType(data['documentId'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('isAdmin'))
        obj.isAdmin = ApiClient.convertToType(data['isAdmin'], 'Boolean');
      if (data.hasOwnProperty('isSuperAdmin'))
        obj.isSuperAdmin = ApiClient.convertToType(data['isSuperAdmin'], 'Boolean');
      if (data.hasOwnProperty('isSalesman'))
        obj.isSalesman = ApiClient.convertToType(data['isSalesman'], 'Boolean');
      if (data.hasOwnProperty('isIntegration'))
        obj.isIntegration = ApiClient.convertToType(data['isIntegration'], 'Boolean');
      if (data.hasOwnProperty('isRegionManager'))
        obj.isRegionManager = ApiClient.convertToType(data['isRegionManager'], 'Boolean');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = UserStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
GetAllUserResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
GetAllUserResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
GetAllUserResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
GetAllUserResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
GetAllUserResponse.prototype.id = undefined;

/**
 * @member {String} name
 */
GetAllUserResponse.prototype.name = undefined;

/**
 * @member {String} documentId
 */
GetAllUserResponse.prototype.documentId = undefined;

/**
 * @member {String} phone
 */
GetAllUserResponse.prototype.phone = undefined;

/**
 * @member {String} email
 */
GetAllUserResponse.prototype.email = undefined;

/**
 * @member {Boolean} isActive
 */
GetAllUserResponse.prototype.isActive = undefined;

/**
 * @member {Boolean} isAdmin
 */
GetAllUserResponse.prototype.isAdmin = undefined;

/**
 * @member {Boolean} isSuperAdmin
 */
GetAllUserResponse.prototype.isSuperAdmin = undefined;

/**
 * @member {Boolean} isSalesman
 */
GetAllUserResponse.prototype.isSalesman = undefined;

/**
 * @member {Boolean} isIntegration
 */
GetAllUserResponse.prototype.isIntegration = undefined;

/**
 * @member {Boolean} isRegionManager
 */
GetAllUserResponse.prototype.isRegionManager = undefined;

/**
 * @member {String} externalCode
 */
GetAllUserResponse.prototype.externalCode = undefined;

/**
 * @member {module:model/UserStatus} status
 */
GetAllUserResponse.prototype.status = undefined;

