/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PriceTableItemStatus} from './PriceTableItemStatus';

/**
 * The GetAllPriceTableItemResponse model module.
 * @module model/GetAllPriceTableItemResponse
 * @version v1
 */
export class GetAllPriceTableItemResponse {
  /**
   * Constructs a new <code>GetAllPriceTableItemResponse</code>.
   * @alias module:model/GetAllPriceTableItemResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAllPriceTableItemResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllPriceTableItemResponse} obj Optional instance to populate.
   * @return {module:model/GetAllPriceTableItemResponse} The populated <code>GetAllPriceTableItemResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAllPriceTableItemResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('paymentPriceTableId'))
        obj.paymentPriceTableId = ApiClient.convertToType(data['paymentPriceTableId'], 'String');
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = PriceTableItemStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
GetAllPriceTableItemResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
GetAllPriceTableItemResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
GetAllPriceTableItemResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
GetAllPriceTableItemResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
GetAllPriceTableItemResponse.prototype.id = undefined;

/**
 * @member {String} paymentPriceTableId
 */
GetAllPriceTableItemResponse.prototype.paymentPriceTableId = undefined;

/**
 * @member {String} productId
 */
GetAllPriceTableItemResponse.prototype.productId = undefined;

/**
 * @member {Number} value
 */
GetAllPriceTableItemResponse.prototype.value = undefined;

/**
 * @member {String} externalCode
 */
GetAllPriceTableItemResponse.prototype.externalCode = undefined;

/**
 * @member {module:model/PriceTableItemStatus} status
 */
GetAllPriceTableItemResponse.prototype.status = undefined;

