/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DatabaseCollector} from './DatabaseCollector';

/**
 * The PostIntegrationConfigRequest model module.
 * @module model/PostIntegrationConfigRequest
 * @version v1
 */
export class PostIntegrationConfigRequest {
  /**
   * Constructs a new <code>PostIntegrationConfigRequest</code>.
   * @alias module:model/PostIntegrationConfigRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostIntegrationConfigRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostIntegrationConfigRequest} obj Optional instance to populate.
   * @return {module:model/PostIntegrationConfigRequest} The populated <code>PostIntegrationConfigRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostIntegrationConfigRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('timerQueriesCollector'))
        obj.timerQueriesCollector = ApiClient.convertToType(data['timerQueriesCollector'], 'Number');
      if (data.hasOwnProperty('databaseCollector'))
        obj.databaseCollector = DatabaseCollector.constructFromObject(data['databaseCollector']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostIntegrationConfigRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostIntegrationConfigRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostIntegrationConfigRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostIntegrationConfigRequest.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PostIntegrationConfigRequest.prototype.id = undefined;

/**
 * @member {Number} timerQueriesCollector
 */
PostIntegrationConfigRequest.prototype.timerQueriesCollector = undefined;

/**
 * @member {module:model/DatabaseCollector} databaseCollector
 */
PostIntegrationConfigRequest.prototype.databaseCollector = undefined;

