/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PriceTableUnloadingStatus} from './PriceTableUnloadingStatus';

/**
 * The PostPriceTableUnloadingRequest model module.
 * @module model/PostPriceTableUnloadingRequest
 * @version v1
 */
export class PostPriceTableUnloadingRequest {
  /**
   * Constructs a new <code>PostPriceTableUnloadingRequest</code>.
   * @alias module:model/PostPriceTableUnloadingRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostPriceTableUnloadingRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostPriceTableUnloadingRequest} obj Optional instance to populate.
   * @return {module:model/PostPriceTableUnloadingRequest} The populated <code>PostPriceTableUnloadingRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostPriceTableUnloadingRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('productGroupId'))
        obj.productGroupId = ApiClient.convertToType(data['productGroupId'], 'String');
      if (data.hasOwnProperty('paymentConditionId'))
        obj.paymentConditionId = ApiClient.convertToType(data['paymentConditionId'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = PriceTableUnloadingStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('valueOfKG'))
        obj.valueOfKG = ApiClient.convertToType(data['valueOfKG'], 'Number');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostPriceTableUnloadingRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostPriceTableUnloadingRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostPriceTableUnloadingRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostPriceTableUnloadingRequest.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PostPriceTableUnloadingRequest.prototype.id = undefined;

/**
 * @member {String} productGroupId
 */
PostPriceTableUnloadingRequest.prototype.productGroupId = undefined;

/**
 * @member {String} paymentConditionId
 */
PostPriceTableUnloadingRequest.prototype.paymentConditionId = undefined;

/**
 * @member {module:model/PriceTableUnloadingStatus} status
 */
PostPriceTableUnloadingRequest.prototype.status = undefined;

/**
 * @member {Number} valueOfKG
 */
PostPriceTableUnloadingRequest.prototype.valueOfKG = undefined;

/**
 * @member {String} externalCode
 */
PostPriceTableUnloadingRequest.prototype.externalCode = undefined;

