/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PriceTableStatus} from './PriceTableStatus';
import {TablePriceOperationTypeEnum} from './TablePriceOperationTypeEnum';

/**
 * The PostPriceTableResponse model module.
 * @module model/PostPriceTableResponse
 * @version v1
 */
export class PostPriceTableResponse {
  /**
   * Constructs a new <code>PostPriceTableResponse</code>.
   * @alias module:model/PostPriceTableResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostPriceTableResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostPriceTableResponse} obj Optional instance to populate.
   * @return {module:model/PostPriceTableResponse} The populated <code>PostPriceTableResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostPriceTableResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('operationType'))
        obj.operationType = TablePriceOperationTypeEnum.constructFromObject(data['operationType']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = PriceTableStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostPriceTableResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostPriceTableResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostPriceTableResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostPriceTableResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PostPriceTableResponse.prototype.id = undefined;

/**
 * @member {String} name
 */
PostPriceTableResponse.prototype.name = undefined;

/**
 * @member {module:model/TablePriceOperationTypeEnum} operationType
 */
PostPriceTableResponse.prototype.operationType = undefined;

/**
 * @member {String} description
 */
PostPriceTableResponse.prototype.description = undefined;

/**
 * @member {String} externalCode
 */
PostPriceTableResponse.prototype.externalCode = undefined;

/**
 * @member {module:model/PriceTableStatus} status
 */
PostPriceTableResponse.prototype.status = undefined;

