/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostUserResetPassword model module.
 * @module model/PostUserResetPassword
 * @version v1
 */
export class PostUserResetPassword {
  /**
   * Constructs a new <code>PostUserResetPassword</code>.
   * @alias module:model/PostUserResetPassword
   * @class
   * @param email {String} 
   * @param password {String} 
   * @param newPassword {String} 
   */
  constructor(email, password, newPassword) {
    this.email = email;
    this.password = password;
    this.newPassword = newPassword;
  }

  /**
   * Constructs a <code>PostUserResetPassword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostUserResetPassword} obj Optional instance to populate.
   * @return {module:model/PostUserResetPassword} The populated <code>PostUserResetPassword</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostUserResetPassword();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('newPassword'))
        obj.newPassword = ApiClient.convertToType(data['newPassword'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
PostUserResetPassword.prototype.email = undefined;

/**
 * @member {String} password
 */
PostUserResetPassword.prototype.password = undefined;

/**
 * @member {String} newPassword
 */
PostUserResetPassword.prototype.newPassword = undefined;

