/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PaymentPriceTableStatus} from './PaymentPriceTableStatus';

/**
 * The PostPaymentPriceTableRequest model module.
 * @module model/PostPaymentPriceTableRequest
 * @version v1
 */
export class PostPaymentPriceTableRequest {
  /**
   * Constructs a new <code>PostPaymentPriceTableRequest</code>.
   * @alias module:model/PostPaymentPriceTableRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostPaymentPriceTableRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostPaymentPriceTableRequest} obj Optional instance to populate.
   * @return {module:model/PostPaymentPriceTableRequest} The populated <code>PostPaymentPriceTableRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostPaymentPriceTableRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('paymentConditionId'))
        obj.paymentConditionId = ApiClient.convertToType(data['paymentConditionId'], 'String');
      if (data.hasOwnProperty('priceTableId'))
        obj.priceTableId = ApiClient.convertToType(data['priceTableId'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = PaymentPriceTableStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostPaymentPriceTableRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostPaymentPriceTableRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostPaymentPriceTableRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostPaymentPriceTableRequest.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PostPaymentPriceTableRequest.prototype.id = undefined;

/**
 * @member {String} paymentConditionId
 */
PostPaymentPriceTableRequest.prototype.paymentConditionId = undefined;

/**
 * @member {String} priceTableId
 */
PostPaymentPriceTableRequest.prototype.priceTableId = undefined;

/**
 * @member {String} externalCode
 */
PostPaymentPriceTableRequest.prototype.externalCode = undefined;

/**
 * @member {module:model/PaymentPriceTableStatus} status
 */
PostPaymentPriceTableRequest.prototype.status = undefined;

