/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostUserSignInRequest model module.
 * @module model/PostUserSignInRequest
 * @version v1
 */
export class PostUserSignInRequest {
  /**
   * Constructs a new <code>PostUserSignInRequest</code>.
   * @alias module:model/PostUserSignInRequest
   * @class
   * @param email {String} 
   * @param password {String} 
   */
  constructor(email, password) {
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>PostUserSignInRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostUserSignInRequest} obj Optional instance to populate.
   * @return {module:model/PostUserSignInRequest} The populated <code>PostUserSignInRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostUserSignInRequest();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
PostUserSignInRequest.prototype.email = undefined;

/**
 * @member {String} password
 */
PostUserSignInRequest.prototype.password = undefined;

