/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentVersion} from './DocumentVersion';
import {ProductEspecification} from './ProductEspecification';
import {ProductStatus} from './ProductStatus';
import {UnitMeasurementTypeEnum} from './UnitMeasurementTypeEnum';

/**
 * The Product model module.
 * @module model/Product
 * @version v1
 */
export class Product {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = DocumentVersion.constructFromObject(data['version']);
      if (data.hasOwnProperty('companyId'))
        obj.companyId = ApiClient.convertToType(data['companyId'], 'String');
      if (data.hasOwnProperty('productGroupId'))
        obj.productGroupId = ApiClient.convertToType(data['productGroupId'], 'String');
      if (data.hasOwnProperty('productLineId'))
        obj.productLineId = ApiClient.convertToType(data['productLineId'], 'String');
      if (data.hasOwnProperty('weightkilograms'))
        obj.weightkilograms = ApiClient.convertToType(data['weightkilograms'], 'Number');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('photo'))
        obj.photo = ApiClient.convertToType(data['photo'], 'String');
      if (data.hasOwnProperty('especification'))
        obj.especification = ApiClient.convertToType(data['especification'], [ProductEspecification]);
      if (data.hasOwnProperty('unitMeasurementType'))
        obj.unitMeasurementType = UnitMeasurementTypeEnum.constructFromObject(data['unitMeasurementType']);
      if (data.hasOwnProperty('status'))
        obj.status = ProductStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Product.prototype.id = undefined;

/**
 * @member {Date} createdAt
 */
Product.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
Product.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
Product.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
Product.prototype.userUpdated = undefined;

/**
 * @member {module:model/DocumentVersion} version
 */
Product.prototype.version = undefined;

/**
 * @member {String} companyId
 */
Product.prototype.companyId = undefined;

/**
 * @member {String} productGroupId
 */
Product.prototype.productGroupId = undefined;

/**
 * @member {String} productLineId
 */
Product.prototype.productLineId = undefined;

/**
 * @member {Number} weightkilograms
 */
Product.prototype.weightkilograms = undefined;

/**
 * @member {String} externalCode
 */
Product.prototype.externalCode = undefined;

/**
 * @member {String} name
 */
Product.prototype.name = undefined;

/**
 * @member {String} description
 */
Product.prototype.description = undefined;

/**
 * @member {String} photo
 */
Product.prototype.photo = undefined;

/**
 * @member {Array.<module:model/ProductEspecification>} especification
 */
Product.prototype.especification = undefined;

/**
 * @member {module:model/UnitMeasurementTypeEnum} unitMeasurementType
 */
Product.prototype.unitMeasurementType = undefined;

/**
 * @member {module:model/ProductStatus} status
 */
Product.prototype.status = undefined;

