/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PurchaseOrderStatus} from './PurchaseOrderStatus';

/**
 * The PurchaseOrderHistory model module.
 * @module model/PurchaseOrderHistory
 * @version v1
 */
export class PurchaseOrderHistory {
  /**
   * Constructs a new <code>PurchaseOrderHistory</code>.
   * @alias module:model/PurchaseOrderHistory
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PurchaseOrderHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PurchaseOrderHistory} obj Optional instance to populate.
   * @return {module:model/PurchaseOrderHistory} The populated <code>PurchaseOrderHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PurchaseOrderHistory();
      if (data.hasOwnProperty('status'))
        obj.status = PurchaseOrderStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('summary'))
        obj.summary = ApiClient.convertToType(data['summary'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/PurchaseOrderStatus} status
 */
PurchaseOrderHistory.prototype.status = undefined;

/**
 * @member {Date} _date
 */
PurchaseOrderHistory.prototype._date = undefined;

/**
 * @member {String} summary
 */
PurchaseOrderHistory.prototype.summary = undefined;

/**
 * @member {String} userId
 */
PurchaseOrderHistory.prototype.userId = undefined;

