/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FreightTableStatus} from './FreightTableStatus';
import {TablePriceOperationTypeEnum} from './TablePriceOperationTypeEnum';

/**
 * The PutFreightTableRequest model module.
 * @module model/PutFreightTableRequest
 * @version v1
 */
export class PutFreightTableRequest {
  /**
   * Constructs a new <code>PutFreightTableRequest</code>.
   * @alias module:model/PutFreightTableRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutFreightTableRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutFreightTableRequest} obj Optional instance to populate.
   * @return {module:model/PutFreightTableRequest} The populated <code>PutFreightTableRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutFreightTableRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('paymentConditionId'))
        obj.paymentConditionId = ApiClient.convertToType(data['paymentConditionId'], 'String');
      if (data.hasOwnProperty('vehicleTypeId'))
        obj.vehicleTypeId = ApiClient.convertToType(data['vehicleTypeId'], 'String');
      if (data.hasOwnProperty('initialKilometer'))
        obj.initialKilometer = ApiClient.convertToType(data['initialKilometer'], 'Number');
      if (data.hasOwnProperty('finalKilometer'))
        obj.finalKilometer = ApiClient.convertToType(data['finalKilometer'], 'Number');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('isFractional'))
        obj.isFractional = ApiClient.convertToType(data['isFractional'], 'Boolean');
      if (data.hasOwnProperty('operationType'))
        obj.operationType = TablePriceOperationTypeEnum.constructFromObject(data['operationType']);
      if (data.hasOwnProperty('status'))
        obj.status = FreightTableStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PutFreightTableRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PutFreightTableRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PutFreightTableRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PutFreightTableRequest.prototype.userUpdated = undefined;

/**
 * @member {String} externalCode
 */
PutFreightTableRequest.prototype.externalCode = undefined;

/**
 * @member {String} id
 */
PutFreightTableRequest.prototype.id = undefined;

/**
 * @member {String} paymentConditionId
 */
PutFreightTableRequest.prototype.paymentConditionId = undefined;

/**
 * @member {String} vehicleTypeId
 */
PutFreightTableRequest.prototype.vehicleTypeId = undefined;

/**
 * @member {Number} initialKilometer
 */
PutFreightTableRequest.prototype.initialKilometer = undefined;

/**
 * @member {Number} finalKilometer
 */
PutFreightTableRequest.prototype.finalKilometer = undefined;

/**
 * @member {Number} value
 */
PutFreightTableRequest.prototype.value = undefined;

/**
 * @member {Boolean} isFractional
 */
PutFreightTableRequest.prototype.isFractional = undefined;

/**
 * @member {module:model/TablePriceOperationTypeEnum} operationType
 */
PutFreightTableRequest.prototype.operationType = undefined;

/**
 * @member {module:model/FreightTableStatus} status
 */
PutFreightTableRequest.prototype.status = undefined;

