/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductEspecification} from './ProductEspecification';
import {ProductStatus} from './ProductStatus';
import {UnitMeasurementTypeEnum} from './UnitMeasurementTypeEnum';

/**
 * The PutProductRequest model module.
 * @module model/PutProductRequest
 * @version v1
 */
export class PutProductRequest {
  /**
   * Constructs a new <code>PutProductRequest</code>.
   * @alias module:model/PutProductRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutProductRequest} obj Optional instance to populate.
   * @return {module:model/PutProductRequest} The populated <code>PutProductRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutProductRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('productGroupId'))
        obj.productGroupId = ApiClient.convertToType(data['productGroupId'], 'String');
      if (data.hasOwnProperty('productLineId'))
        obj.productLineId = ApiClient.convertToType(data['productLineId'], 'String');
      if (data.hasOwnProperty('weightkilograms'))
        obj.weightkilograms = ApiClient.convertToType(data['weightkilograms'], 'Number');
      if (data.hasOwnProperty('externalCode'))
        obj.externalCode = ApiClient.convertToType(data['externalCode'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('unitMeasurementType'))
        obj.unitMeasurementType = UnitMeasurementTypeEnum.constructFromObject(data['unitMeasurementType']);
      if (data.hasOwnProperty('status'))
        obj.status = ProductStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('photo'))
        obj.photo = ApiClient.convertToType(data['photo'], 'String');
      if (data.hasOwnProperty('especification'))
        obj.especification = ApiClient.convertToType(data['especification'], [ProductEspecification]);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PutProductRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PutProductRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PutProductRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PutProductRequest.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PutProductRequest.prototype.id = undefined;

/**
 * @member {String} productGroupId
 */
PutProductRequest.prototype.productGroupId = undefined;

/**
 * @member {String} productLineId
 */
PutProductRequest.prototype.productLineId = undefined;

/**
 * @member {Number} weightkilograms
 */
PutProductRequest.prototype.weightkilograms = undefined;

/**
 * @member {String} externalCode
 */
PutProductRequest.prototype.externalCode = undefined;

/**
 * @member {String} name
 */
PutProductRequest.prototype.name = undefined;

/**
 * @member {String} description
 */
PutProductRequest.prototype.description = undefined;

/**
 * @member {module:model/UnitMeasurementTypeEnum} unitMeasurementType
 */
PutProductRequest.prototype.unitMeasurementType = undefined;

/**
 * @member {module:model/ProductStatus} status
 */
PutProductRequest.prototype.status = undefined;

/**
 * @member {String} photo
 */
PutProductRequest.prototype.photo = undefined;

/**
 * @member {Array.<module:model/ProductEspecification>} especification
 */
PutProductRequest.prototype.especification = undefined;

