/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PutTemplateRequest model module.
 * @module model/PutTemplateRequest
 * @version v1
 */
export class PutTemplateRequest {
  /**
   * Constructs a new <code>PutTemplateRequest</code>.
   * @alias module:model/PutTemplateRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutTemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutTemplateRequest} obj Optional instance to populate.
   * @return {module:model/PutTemplateRequest} The populated <code>PutTemplateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutTemplateRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('businessId'))
        obj.businessId = ApiClient.convertToType(data['businessId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PutTemplateRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PutTemplateRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PutTemplateRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PutTemplateRequest.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
PutTemplateRequest.prototype.id = undefined;

/**
 * @member {String} name
 */
PutTemplateRequest.prototype.name = undefined;

/**
 * @member {Number} businessId
 */
PutTemplateRequest.prototype.businessId = undefined;

