/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DatabaseConnection', function() {
      beforeEach(function() {
        instance = new TepsalesserviceApi.DatabaseConnection();
      });

      it('should create an instance of DatabaseConnection', function() {
        // TODO: update the code to test DatabaseConnection
        expect(instance).to.be.a(TepsalesserviceApi.DatabaseConnection);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property server (base name: "server")', function() {
        // TODO: update the code to test the property server
        expect(instance).to.have.property('server');
        // expect(instance.server).to.be(expectedValueLiteral);
      });

      it('should have the property port (base name: "port")', function() {
        // TODO: update the code to test the property port
        expect(instance).to.have.property('port');
        // expect(instance.port).to.be(expectedValueLiteral);
      });

      it('should have the property user (base name: "user")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property commandTimeout (base name: "commandTimeout")', function() {
        // TODO: update the code to test the property commandTimeout
        expect(instance).to.have.property('commandTimeout');
        // expect(instance.commandTimeout).to.be(expectedValueLiteral);
      });

      it('should have the property minPoolSize (base name: "minPoolSize")', function() {
        // TODO: update the code to test the property minPoolSize
        expect(instance).to.have.property('minPoolSize');
        // expect(instance.minPoolSize).to.be(expectedValueLiteral);
      });

      it('should have the property maxPoolSize (base name: "maxPoolSize")', function() {
        // TODO: update the code to test the property maxPoolSize
        expect(instance).to.have.property('maxPoolSize');
        // expect(instance.maxPoolSize).to.be(expectedValueLiteral);
      });

    });
  });

}));
