/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetAllProductResponse', function() {
      beforeEach(function() {
        instance = new TepsalesserviceApi.GetAllProductResponse();
      });

      it('should create an instance of GetAllProductResponse', function() {
        // TODO: update the code to test GetAllProductResponse
        expect(instance).to.be.a(TepsalesserviceApi.GetAllProductResponse);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property userCreated (base name: "userCreated")', function() {
        // TODO: update the code to test the property userCreated
        expect(instance).to.have.property('userCreated');
        // expect(instance.userCreated).to.be(expectedValueLiteral);
      });

      it('should have the property userUpdated (base name: "userUpdated")', function() {
        // TODO: update the code to test the property userUpdated
        expect(instance).to.have.property('userUpdated');
        // expect(instance.userUpdated).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property productGroupId (base name: "productGroupId")', function() {
        // TODO: update the code to test the property productGroupId
        expect(instance).to.have.property('productGroupId');
        // expect(instance.productGroupId).to.be(expectedValueLiteral);
      });

      it('should have the property productLineId (base name: "productLineId")', function() {
        // TODO: update the code to test the property productLineId
        expect(instance).to.have.property('productLineId');
        // expect(instance.productLineId).to.be(expectedValueLiteral);
      });

      it('should have the property weightkilograms (base name: "weightkilograms")', function() {
        // TODO: update the code to test the property weightkilograms
        expect(instance).to.have.property('weightkilograms');
        // expect(instance.weightkilograms).to.be(expectedValueLiteral);
      });

      it('should have the property externalCode (base name: "externalCode")', function() {
        // TODO: update the code to test the property externalCode
        expect(instance).to.have.property('externalCode');
        // expect(instance.externalCode).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property unitMeasurementType (base name: "unitMeasurementType")', function() {
        // TODO: update the code to test the property unitMeasurementType
        expect(instance).to.have.property('unitMeasurementType');
        // expect(instance.unitMeasurementType).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property photo (base name: "photo")', function() {
        // TODO: update the code to test the property photo
        expect(instance).to.have.property('photo');
        // expect(instance.photo).to.be(expectedValueLiteral);
      });

      it('should have the property especification (base name: "especification")', function() {
        // TODO: update the code to test the property especification
        expect(instance).to.have.property('especification');
        // expect(instance.especification).to.be(expectedValueLiteral);
      });

    });
  });

}));
