/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.DistribuitionCenterClientAddressApi();
  });

  describe('(package)', function() {
    describe('DistribuitionCenterClientAddressApi', function() {
      describe('getByIdDistribuitionCenterClientAddress', function() {
        it('should call getByIdDistribuitionCenterClientAddress successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdDistribuitionCenterClientAddress call and complete the assertions
          /*
          var opts = {};

          instance.getByIdDistribuitionCenterClientAddress(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllDistribuitionCenterClientAddressResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressAllGet', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressAllGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressAllGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressAllGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TepsalesserviceApi.GetAllDistribuitionCenterClientAddressResponse);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressIdDelete', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressIdPatch', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressIdPut', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressIdPut call
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressPagedGet', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressPagedGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressPagedGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressPagedGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedDistribuitionCenterClientAddressResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1DistribuitionCenterClientAddressPost', function() {
        it('should call tepsalesV1DistribuitionCenterClientAddressPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1DistribuitionCenterClientAddressPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1DistribuitionCenterClientAddressPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostDistribuitionCenterClientAddressResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
