/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.NotificationApi();
  });

  describe('(package)', function() {
    describe('NotificationApi', function() {
      describe('getByIdNotification', function() {
        it('should call getByIdNotification successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdNotification call and complete the assertions
          /*
          var opts = {};

          instance.getByIdNotification(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllNotificationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1NotificationsGet', function() {
        it('should call tepsalesV1NotificationsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1NotificationsGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1NotificationsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedNotificationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1NotificationsIdDelete', function() {
        it('should call tepsalesV1NotificationsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1NotificationsIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1NotificationsIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1NotificationsIdPatch', function() {
        it('should call tepsalesV1NotificationsIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1NotificationsIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1NotificationsIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1NotificationsIdPut', function() {
        it('should call tepsalesV1NotificationsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1NotificationsIdPut call
          /*
          var opts = {};

          instance.tepsalesV1NotificationsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1NotificationsPost', function() {
        it('should call tepsalesV1NotificationsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1NotificationsPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1NotificationsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostNotificationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
