/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.PaymentConditionApi();
  });

  describe('(package)', function() {
    describe('PaymentConditionApi', function() {
      describe('getByIdPaymentCondition', function() {
        it('should call getByIdPaymentCondition successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdPaymentCondition call and complete the assertions
          /*
          var opts = {};

          instance.getByIdPaymentCondition(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPaymentConditionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsAllGet', function() {
        it('should call tepsalesV1PaymentConditionsAllGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsAllGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsAllGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TepsalesserviceApi.GetAllPaymentConditionResponse);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsIdDelete', function() {
        it('should call tepsalesV1PaymentConditionsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsIdPatch', function() {
        it('should call tepsalesV1PaymentConditionsIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsIdPut', function() {
        it('should call tepsalesV1PaymentConditionsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsIdPut call
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsPagedGet', function() {
        it('should call tepsalesV1PaymentConditionsPagedGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsPagedGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsPagedGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedPaymentConditionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PaymentConditionsPost', function() {
        it('should call tepsalesV1PaymentConditionsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PaymentConditionsPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PaymentConditionsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostPaymentConditionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
