/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.ProductGroupApi();
  });

  describe('(package)', function() {
    describe('ProductGroupApi', function() {
      describe('getByExternalCodeProductGroupController', function() {
        it('should call getByExternalCodeProductGroupController successfully', function(done) {
          // TODO: uncomment, update parameter values for getByExternalCodeProductGroupController call and complete the assertions
          /*
          var opts = {};

          instance.getByExternalCodeProductGroupController(externalCode, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllProductGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getByIdProductGroup', function() {
        it('should call getByIdProductGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdProductGroup call and complete the assertions
          /*
          var opts = {};

          instance.getByIdProductGroup(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllProductGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsAllGet', function() {
        it('should call tepsalesV1ProductGroupsAllGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsAllGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsAllGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TepsalesserviceApi.GetAllProductGroupResponse);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsIdDelete', function() {
        it('should call tepsalesV1ProductGroupsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsIdPatch', function() {
        it('should call tepsalesV1ProductGroupsIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsIdPut', function() {
        it('should call tepsalesV1ProductGroupsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsIdPut call
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsPagedGet', function() {
        it('should call tepsalesV1ProductGroupsPagedGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsPagedGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsPagedGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedProductGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1ProductGroupsPost', function() {
        it('should call tepsalesV1ProductGroupsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1ProductGroupsPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1ProductGroupsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostProductGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
