/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.PurchaseOrderApi();
  });

  describe('(package)', function() {
    describe('PurchaseOrderApi', function() {
      describe('getByIdPurchaseOrder', function() {
        it('should call getByIdPurchaseOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdPurchaseOrder call and complete the assertions
          /*
          var opts = {};

          instance.getByIdPurchaseOrder(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPurchaseOrderResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersAllGet', function() {
        it('should call tepsalesV1PurchaseordersAllGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersAllGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersAllGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TepsalesserviceApi.GetAllPurchaseOrderResponse);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdApprovePost', function() {
        it('should call tepsalesV1PurchaseordersIdApprovePost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdApprovePost call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdApprovePost(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdCancelPost', function() {
        it('should call tepsalesV1PurchaseordersIdCancelPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdCancelPost call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdCancelPost(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdDelete', function() {
        it('should call tepsalesV1PurchaseordersIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdPatch', function() {
        it('should call tepsalesV1PurchaseordersIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdPut', function() {
        it('should call tepsalesV1PurchaseordersIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdPut call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdRefusedPost', function() {
        it('should call tepsalesV1PurchaseordersIdRefusedPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdRefusedPost call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdRefusedPost(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersIdSendtoapprovePost', function() {
        it('should call tepsalesV1PurchaseordersIdSendtoapprovePost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersIdSendtoapprovePost call
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersIdSendtoapprovePost(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersPagedGet', function() {
        it('should call tepsalesV1PurchaseordersPagedGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersPagedGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersPagedGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedPurchaseOrderResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1PurchaseordersPost', function() {
        it('should call tepsalesV1PurchaseordersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1PurchaseordersPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1PurchaseordersPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostPurchaseOrderResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
