/*
 * Tep.Sales.Service API
 * Tep.Sales.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@tecnoepec.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TepsalesserviceApi);
  }
}(this, function(expect, TepsalesserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TepsalesserviceApi.VehicleTypeApi();
  });

  describe('(package)', function() {
    describe('VehicleTypeApi', function() {
      describe('getByIdVehicleType', function() {
        it('should call getByIdVehicleType successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdVehicleType call and complete the assertions
          /*
          var opts = {};

          instance.getByIdVehicleType(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllVehicleTypeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesAllGet', function() {
        it('should call tepsalesV1VehicleTypesAllGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesAllGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesAllGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TepsalesserviceApi.GetAllVehicleTypeResponse);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesIdDelete', function() {
        it('should call tepsalesV1VehicleTypesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesIdDelete call
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesIdPatch', function() {
        it('should call tepsalesV1VehicleTypesIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesIdPatch call
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesIdPut', function() {
        it('should call tepsalesV1VehicleTypesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesIdPut call
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesPagedGet', function() {
        it('should call tepsalesV1VehicleTypesPagedGet successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesPagedGet call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesPagedGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.GetAllPagedVehicleTypeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tepsalesV1VehicleTypesPost', function() {
        it('should call tepsalesV1VehicleTypesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for tepsalesV1VehicleTypesPost call and complete the assertions
          /*
          var opts = {};

          instance.tepsalesV1VehicleTypesPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TepsalesserviceApi.PostVehicleTypeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
